# Generated by Django 2.2.2 on 2019-06-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jokes',
            fields=[
                ('joke_id', models.AutoField(primary_key=True, serialize=False)),
                ('joke_content', models.CharField(max_length=200)),
            ],
        ),
    ]
