# Generated by Django 2.2.2 on 2019-06-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokes',
            name='joke_content',
            field=models.TextField(max_length=2000),
        ),
    ]
